--+============================================================================+
--|                                                                            |
--|                     This file was generated by Chips                       |
--|                                                                            |
--|                                  Chips                                     |
--|                                                                            |
--|                      http://github.com/dawsonjon/chips                     |
--|                                                                            |
--|                                                             Python powered |
--+============================================================================+

-- generated by python streams library
-- date generated  : UTC 2011-11-30 21:03:04
-- platform        : linux2
-- python version  : 2.7.2+ (default, Oct 4 2011, 20:06:09) [GCC 4.6.1]
-- streams version : 0.1.2

--+============================================================================+
--|                             **END OF HEADER**                              |
--+============================================================================+

--                                   ***                                       

--+============================================================================+
--|                    **START OF EXTERNAL DEPENDENCIES**                      |
--+============================================================================+



--+============================================================================+
--|                     **END OF EXTERNAL DEPENDENCIES**                       |
--+============================================================================+

--                                   ***                                       

--+============================================================================+
--|                     **START OF AUTO GENERATED CODE**                       |
--+============================================================================+

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity STREAMS_VHDL_MODEL is
  port(
    CLK           : in  std_logic;
    RST           : in  std_logic;
    TX : out std_logic;
    RX : in std_logic
  );
end entity STREAMS_VHDL_MODEL;

architecture RTL of STREAMS_VHDL_MODEL is


  --returns the greater of the two parameters
  function MAX(
    A : integer;
    B : integer) return integer is
  begin
    if A > B then
      return A;
    else
      return B;
    end if;
  end MAX;

  --returns a std_logic_vector sum of the two parameters
  function ABSOLUTE(
    A : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(abs(signed(A)));
  end ABSOLUTE;

  --returns a std_logic_vector sum of the two parameters
  function ADD(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(
      resize(signed(A), MAX(A'length, B'length) + 1) + 
      resize(signed(B), MAX(A'length, B'length) + 1));
    end ADD;

  --returns a std_logic_vector product of the two parameters
  function MUL(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(
      signed(A) *
      signed(B));
    end MUL;

  --returns a std_logic_vector difference of the two parameters
  function SUB(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(
      resize(signed(A), MAX(A'length, B'length) + 1) - 
      resize(signed(B), MAX(A'length, B'length) + 1));
  end SUB;

  --returns A shifted right (arithmetic) by A
  function SR(
    A  : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(shift_right(signed(A), to_integer(signed(B))));
  end SR;

  --returns A shifted left by B
  function SL(
    A  : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(shift_left(signed(A), to_integer(signed(B))));
  end SL;

  --returns bitwise and of A and B
  --(A and B are resized to the length of the larger first)
  function BAND(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) and
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)));
  end BAND;

  --returns bitwise or of A and B
  --(A and B are resized to the length of the larger first)
  function BOR(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) or
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)));
  end BOR;

  --returns bitwise xor of A and B
  --(A and B are resized to the length of the larger first)
  function BXOR(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    return std_logic_vector(
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) xor
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)));
  end BXOR;

  --equality comparison of A and B
  --(A and B are resized to the length of the larger first)
  function EQ(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    if 
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) =
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end EQ;

  --inequality comparison of A and B
  --(A and B are resized to the length of the larger first)
  function NE(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    if 
    resize(signed(A), MAX(A'LENGTH, B'LENGTH)) /=
    resize(signed(B), MAX(A'LENGTH, B'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end NE;

  --greater than comparison of A and B
  --(A and B are resized to the length of the larger first)
  function GT(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    if 
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) >
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end GT;

  --greater than or equal comparison of A and B
  --(A and B are resized to the length of the larger first)
  function GE(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    if 
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) >=
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end GE;

  --less than comparison of A and B
  --(A and B are resized to the length of the larger first)
  function LT(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    if 
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) <
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end LT;

  --less than or equal comparison of A and B
  --(A and B are resized to the length of the larger first)
  function LE(
    A : std_logic_vector; 
    B : std_logic_vector) return std_logic_vector is
  begin
    if 
      resize(signed(A), MAX(A'LENGTH, B'LENGTH)) <=
      resize(signed(B), MAX(A'LENGTH, B'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end LE;

  --logical negation
  function LNOT(
    A : std_logic_vector) return std_logic_vector is
  begin
    if 
      A = std_logic_vector(to_signed(0, A'LENGTH)) then
      return "1";
    else
      return "0";
    end if;
  end LNOT;

  --resize A to B bits
  function STD_RESIZE(
    A : std_logic_vector; 
    B : integer) return std_logic_vector is
  begin
    return std_logic_vector(
      resize(signed(A), B));
  end STD_RESIZE;

  type BINARY_STATE_TYPE is (BINARY_INPUT, BINARY_OUTPUT);
  type UNARY_STATE_TYPE is (UNARY_INPUT, UNARY_OUTPUT);
  type TEE_STATE_TYPE is (TEE_INPUT_A, TEE_WAIT_YZ, TEE_WAIT_Y, TEE_WAIT_Z);
  type DIVIDER_STATE_TYPE is (READ_A_B, DIVIDE_1, DIVIDE_2, WRITE_Z);
  type SERIAL_IN_STATE_TYPE is (IDLE, START, RX0, RX1, RX2, RX3, RX4, RX5, RX6, RX7, STOP, OUTPUT_DATA);
  type SERIAL_OUT_STATE_TYPE is (IDLE, START, WAIT_EN, TX0, TX1, TX2, TX3, TX4, TX5, TX6, TX7, STOP);
  type PRINTER_STATE_TYPE is (INPUT_A, SHIFT, OUTPUT_SIGN, OUTPUT_Z, OUTPUT_NL);
  type HEX_PRINTER_STATE_TYPE is (INPUT_A, OUTPUT_SIGN, OUTPUT_DIGITS);

  constant TIMER_1us_MAX : integer := 49;
  signal TIMER_1us_COUNT : integer range 0 to TIMER_1us_MAX;
  signal TIMER_1us : std_logic;
  constant TIMER_10us_MAX : integer := 49;
  signal TIMER_10us_COUNT : integer range 0 to TIMER_1us_MAX;
  signal TIMER_10us : std_logic;
  constant TIMER_100us_MAX : integer := 49;
  signal TIMER_100us_COUNT : integer range 0 to TIMER_1us_MAX;
  signal TIMER_100us : std_logic;
  constant TIMER_1ms_MAX : integer := 49;
  signal TIMER_1ms_COUNT : integer range 0 to TIMER_1us_MAX;
  signal TIMER_1ms : std_logic;



  signal STATE_4           : SERIAL_OUT_STATE_TYPE;
  constant CLOCK_DIVIDER_4 : Unsigned(11 downto 0) := To_unsigned(433, 12);
  signal BAUD_COUNT_4      : Unsigned(11 downto 0);
  signal DATA_4            : std_logic_vector(7 downto 0);
  signal X16CLK_EN_4       : std_logic;
  signal STREAM_3     : std_logic_vector(7 downto 0);
  signal STREAM_3_STB : std_logic;
  signal STREAM_3_ACK : std_logic;

  signal STATE_0           : SERIAL_IN_STATE_TYPE;
  signal STREAM_0          : std_logic_vector(7 downto 0);
  signal STREAM_0_STB      : std_logic;
  signal STREAM_0_ACK      : std_logic;
  signal COUNT_0           : integer Range 0 to 3;
  signal BIT_SPACING_0     : integer Range 0 to 15;
  signal INT_SERIAL_0      : std_logic;
  signal SERIAL_DEGLITCH_0 : std_logic_Vector(1 downto 0);
  constant CLOCK_DIVIDER_0 : unsigned(11 downto 0) := To_unsigned(26, 12);
  signal BAUD_COUNT_0      : unsigned(11 downto 0);
  signal X16CLK_EN_0       : std_logic;
  signal STREAM_1       : std_logic_vector(15 downto 0);
  signal STREAM_1_STB   : std_logic;
  signal STREAM_1_ACK   : std_logic;
  constant OP_IMM_2 : std_logic_vector(4 downto 0) := "00000";
  constant OP_MOVE_2 : std_logic_vector(4 downto 0) := "00001";
  constant OP_GT_2 : std_logic_vector(4 downto 0) := "00010";
  constant OP_BOR_2 : std_logic_vector(4 downto 0) := "00011";
  constant OP_LNOT_2 : std_logic_vector(4 downto 0) := "00100";
  constant OP_JMPF_2 : std_logic_vector(4 downto 0) := "00101";
  constant OP_JMP_2 : std_logic_vector(4 downto 0) := "00110";
  constant OP_BAND_2 : std_logic_vector(4 downto 0) := "00111";
  constant OP_GE_2 : std_logic_vector(4 downto 0) := "01000";
  constant OP_MUL_2 : std_logic_vector(4 downto 0) := "01001";
  constant OP_ADD_2 : std_logic_vector(4 downto 0) := "01010";
  constant OP_SUB_2 : std_logic_vector(4 downto 0) := "01011";
  constant OP_NE_2 : std_logic_vector(4 downto 0) := "01100";
  constant OP_EQ_2 : std_logic_vector(4 downto 0) := "01101";
  constant OP_DIV_2 : std_logic_vector(4 downto 0) := "01110";
  constant OP_WAIT_US_2 : std_logic_vector(4 downto 0) := "01111";
  constant OP_NOOP_2 : std_logic_vector(4 downto 0) := "10000";
  constant OP_READ_0_2 : std_logic_vector(4 downto 0) := "10001";
  constant OP_WRITE_1_2 : std_logic_vector(4 downto 0) := "10010";
  type PROCESS_2_STATE_TYPE is (STALL, EXECUTE, DIVIDE_0, DIVIDE_1, DIVIDE_2, WAIT_US, READ_STREAM_0, ACK_STREAM_0, WRITE_STREAM_1);
  type INSTRUCTIONS_TYPE_2  is array (0 to 668) of std_logic_vector(24 downto 0);
  type REGISTERS_TYPE_2     is array (0 to 15) of std_logic_vector(15 downto 0);

  --Pipeline stage 0 outputs
  signal OPERATION_0_2  : std_logic_vector(4 downto 0);
  signal SRCA_0_2       : std_logic_vector(3 downto 0);
  signal SRCB_0_2       : std_logic_vector(3 downto 0);
  signal IMMEDIATE_0_2  : std_logic_vector(15 downto 0);
  --Pipeline stage 1 outputs
  signal OPERATION_1_2    : std_logic_vector(4 downto 0);
  signal IMMEDIATE_1_2    : std_logic_vector(15 downto 0);
  signal REGA_1_2         : std_logic_vector(15 downto 0);
  signal REGB_1_2         : std_logic_vector(15 downto 0);
  signal DEST_1_2         : std_logic_vector(3 downto 0);
  --Pipeline stage 2 outputs
  signal OPERATION_2_2    : std_logic_vector(4 downto 0);
  signal IMMEDIATE_2_2    : std_logic_vector(15 downto 0);
  signal REGA_2_2         : std_logic_vector(15 downto 0);
  signal REGB_2_2         : std_logic_vector(15 downto 0);
  signal DEST_2_2         : std_logic_vector(3 downto 0);
  signal PRODUCT_A_2_2    : signed(35 downto 0);
  signal PRODUCT_B_2_2    : signed(35 downto 0);
  signal PRODUCT_C_2_2    : signed(35 downto 0);
  signal PRODUCT_D_2_2    : signed(35 downto 0);
  --Pipeline stage 3 outputs
  signal RESULT_3_2       : std_logic_vector(15 downto 0);
  signal DEST_3_2         : std_logic_vector(3 downto 0);
  signal REGISTER_EN_3_2  : std_logic;
  signal STATE_2          : PROCESS_2_STATE_TYPE;
  signal PC_2             : unsigned(9 downto 0);
  signal ZERO_2           : std_logic;
  signal A_2              : std_logic_vector(15 downto 0);
  signal B_2              : std_logic_vector(15 downto 0);
  signal QUOTIENT_2       : std_logic_vector(15 downto 0);
  signal SHIFTER_2        : std_logic_vector(15 downto 0);
  signal REMAINDER_2      : std_logic_vector(15 downto 0);
  signal COUNT_2          : integer range 0 to 16;
  signal SIGN_2           : std_logic;
  signal INSTRUCTIONS_2   : INSTRUCTIONS_TYPE_2 := (
0 => OP_IMM_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
1 => OP_IMM_2 & "0010" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
2 => OP_IMM_2 & "0011" & "0000000000000000", -- file: ./example_3_serial_clock.py line: 14
3 => OP_IMM_2 & "0100" & "0000000000000000", -- file: ./example_3_serial_clock.py line: 15
4 => OP_IMM_2 & "0101" & "0000000000000000", -- file: ./example_3_serial_clock.py line: 16
5 => OP_IMM_2 & "0110" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
6 => OP_IMM_2 & "0111" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
7 => OP_IMM_2 & "1000" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 204
8 => OP_IMM_2 & "1001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
9 => OP_IMM_2 & "1010" & "0000000000000000", -- file: ./example_3_serial_clock.py line: 17
10 => OP_IMM_2 & "1011" & "0000000000000000", -- file: ./example_3_serial_clock.py line: 18
11 => OP_IMM_2 & "1100" & "0000000001000101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
12 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
13 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
14 => OP_IMM_2 & "1100" & "0000000001101110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
15 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
16 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
17 => OP_IMM_2 & "1100" & "0000000001110100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
18 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
19 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
20 => OP_IMM_2 & "1100" & "0000000001100101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
21 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
22 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
23 => OP_IMM_2 & "1100" & "0000000001110010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
24 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
25 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
26 => OP_IMM_2 & "1100" & "0000000000100000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
27 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
28 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
29 => OP_IMM_2 & "1100" & "0000000001110100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
30 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
31 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
32 => OP_IMM_2 & "1100" & "0000000001101001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
33 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
34 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
35 => OP_IMM_2 & "1100" & "0000000001101101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
36 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
37 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
38 => OP_IMM_2 & "1100" & "0000000001100101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
39 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
40 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
41 => OP_IMM_2 & "1100" & "0000000000100000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
42 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
43 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
44 => OP_IMM_2 & "1100" & "0000000001101000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
45 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
46 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
47 => OP_IMM_2 & "1100" & "0000000001101111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
48 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
49 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
50 => OP_IMM_2 & "1100" & "0000000001110101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
51 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
52 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
53 => OP_IMM_2 & "1100" & "0000000001110010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
54 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
55 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
56 => OP_IMM_2 & "1100" & "0000000001110011", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
57 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
58 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
59 => OP_IMM_2 & "1100" & "0000000000111010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
60 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
61 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
62 => OP_IMM_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
63 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
64 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
65 => OP_IMM_2 & "1100" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
66 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
67 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
68 => OP_READ_0_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 399
69 => OP_IMM_2 & "1100" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
70 => OP_MOVE_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
71 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
72 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
73 => OP_MOVE_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
74 => OP_IMM_2 & "1110" & "0000000000111001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
75 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
76 => OP_GT_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 210
77 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
78 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 198
79 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
80 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
81 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
82 => OP_JMPF_2 & "1100" & "0000000001010101", -- file: None line: None
83 => OP_JMP_2 & "0000" & "0000000001010111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
84 => OP_JMP_2 & "0000" & "0000000001010101", -- file: None line: None
85 => OP_READ_0_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 399
86 => OP_JMP_2 & "0000" & "0000000001000101", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
87 => OP_MOVE_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
88 => OP_IMM_2 & "1101" & "0000000000001111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
89 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
90 => OP_BAND_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 196
91 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
92 => OP_MOVE_2 & "0010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
93 => OP_READ_0_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 399
94 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
95 => OP_MOVE_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
96 => OP_IMM_2 & "1101" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
97 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
98 => OP_GE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 212
99 => OP_IMM_2 & "1101" & "0000000000111001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
100 => OP_MOVE_2 & "1110" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
101 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
102 => OP_GE_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 216
103 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
104 => OP_BAND_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 196
105 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
106 => OP_JMPF_2 & "1100" & "0000000001111100", -- file: None line: None
107 => OP_MOVE_2 & "1100" & "0000000000000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
108 => OP_IMM_2 & "1101" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
109 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
110 => OP_MUL_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 190
111 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
112 => OP_MOVE_2 & "0010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
113 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
114 => OP_MOVE_2 & "1100" & "0000000000000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
115 => OP_MOVE_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
116 => OP_IMM_2 & "1110" & "0000000000001111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
117 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
118 => OP_BAND_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 196
119 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
120 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
121 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
122 => OP_MOVE_2 & "0010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
123 => OP_JMP_2 & "0000" & "0000000010000001", -- file: None line: None
124 => OP_IMM_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
125 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
126 => OP_JMPF_2 & "1100" & "0000000010000001", -- file: None line: None
127 => OP_JMP_2 & "0000" & "0000000010000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 305
128 => OP_JMP_2 & "0000" & "0000000010000001", -- file: None line: None
129 => OP_JMP_2 & "0000" & "0000000001011101", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 305
130 => OP_MOVE_2 & "1100" & "0000000000000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
131 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
132 => OP_MOVE_2 & "0011" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
133 => OP_IMM_2 & "1100" & "0000000001000101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
134 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
135 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
136 => OP_IMM_2 & "1100" & "0000000001101110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
137 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
138 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
139 => OP_IMM_2 & "1100" & "0000000001110100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
140 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
141 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
142 => OP_IMM_2 & "1100" & "0000000001100101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
143 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
144 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
145 => OP_IMM_2 & "1100" & "0000000001110010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
146 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
147 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
148 => OP_IMM_2 & "1100" & "0000000000100000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
149 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
150 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
151 => OP_IMM_2 & "1100" & "0000000001110100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
152 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
153 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
154 => OP_IMM_2 & "1100" & "0000000001101001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
155 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
156 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
157 => OP_IMM_2 & "1100" & "0000000001101101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
158 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
159 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
160 => OP_IMM_2 & "1100" & "0000000001100101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
161 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
162 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
163 => OP_IMM_2 & "1100" & "0000000000100000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
164 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
165 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
166 => OP_IMM_2 & "1100" & "0000000001101101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
167 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
168 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
169 => OP_IMM_2 & "1100" & "0000000001101001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
170 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
171 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
172 => OP_IMM_2 & "1100" & "0000000001101110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
173 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
174 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
175 => OP_IMM_2 & "1100" & "0000000001110101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
176 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
177 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
178 => OP_IMM_2 & "1100" & "0000000001110100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
179 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
180 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
181 => OP_IMM_2 & "1100" & "0000000001100101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
182 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
183 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
184 => OP_IMM_2 & "1100" & "0000000001110011", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
185 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
186 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
187 => OP_IMM_2 & "1100" & "0000000000111010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
188 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
189 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
190 => OP_IMM_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
191 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
192 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
193 => OP_IMM_2 & "1100" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
194 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
195 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
196 => OP_READ_0_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 399
197 => OP_IMM_2 & "1100" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
198 => OP_MOVE_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
199 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
200 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
201 => OP_MOVE_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
202 => OP_IMM_2 & "1110" & "0000000000111001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
203 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
204 => OP_GT_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 210
205 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
206 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 198
207 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
208 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
209 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
210 => OP_JMPF_2 & "1100" & "0000000011010101", -- file: None line: None
211 => OP_JMP_2 & "0000" & "0000000011010111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
212 => OP_JMP_2 & "0000" & "0000000011010101", -- file: None line: None
213 => OP_READ_0_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 399
214 => OP_JMP_2 & "0000" & "0000000011000101", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
215 => OP_MOVE_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
216 => OP_IMM_2 & "1101" & "0000000000001111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
217 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
218 => OP_BAND_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 196
219 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
220 => OP_MOVE_2 & "0010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
221 => OP_READ_0_2 & "0001" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 399
222 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
223 => OP_MOVE_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
224 => OP_IMM_2 & "1101" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
225 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
226 => OP_GE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 212
227 => OP_IMM_2 & "1101" & "0000000000111001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
228 => OP_MOVE_2 & "1110" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
229 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
230 => OP_GE_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 216
231 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
232 => OP_BAND_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 196
233 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
234 => OP_JMPF_2 & "1100" & "0000000011111100", -- file: None line: None
235 => OP_MOVE_2 & "1100" & "0000000000000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
236 => OP_IMM_2 & "1101" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
237 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
238 => OP_MUL_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 190
239 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
240 => OP_MOVE_2 & "0010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
241 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
242 => OP_MOVE_2 & "1100" & "0000000000000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
243 => OP_MOVE_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 287
244 => OP_IMM_2 & "1110" & "0000000000001111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
245 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
246 => OP_BAND_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 196
247 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
248 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
249 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
250 => OP_MOVE_2 & "0010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
251 => OP_JMP_2 & "0000" & "0000000100000001", -- file: None line: None
252 => OP_IMM_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
253 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
254 => OP_JMPF_2 & "1100" & "0000000100000001", -- file: None line: None
255 => OP_JMP_2 & "0000" & "0000000100000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 305
256 => OP_JMP_2 & "0000" & "0000000100000001", -- file: None line: None
257 => OP_JMP_2 & "0000" & "0000000011011101", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 305
258 => OP_MOVE_2 & "1100" & "0000000000000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 288
259 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
260 => OP_MOVE_2 & "0100" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
261 => OP_IMM_2 & "1100" & "0000000000011000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
262 => OP_MOVE_2 & "1101" & "0000000000000011", -- file: ./example_3_serial_clock.py line: 14
263 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
264 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
265 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
266 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
267 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
268 => OP_JMPF_2 & "1100" & "0000000100001111", -- file: None line: None
269 => OP_JMP_2 & "0000" & "0000001010010110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
270 => OP_JMP_2 & "0000" & "0000000100001111", -- file: None line: None
271 => OP_IMM_2 & "1100" & "0000000000111100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
272 => OP_MOVE_2 & "1101" & "0000000000000100", -- file: ./example_3_serial_clock.py line: 15
273 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
274 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
275 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
276 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
277 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
278 => OP_JMPF_2 & "1100" & "0000000100011001", -- file: None line: None
279 => OP_JMP_2 & "0000" & "0000001010001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
280 => OP_JMP_2 & "0000" & "0000000100011001", -- file: None line: None
281 => OP_IMM_2 & "1100" & "0000000000111100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
282 => OP_MOVE_2 & "1101" & "0000000000000101", -- file: ./example_3_serial_clock.py line: 16
283 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
284 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
285 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
286 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
287 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
288 => OP_JMPF_2 & "1100" & "0000000100100011", -- file: None line: None
289 => OP_JMP_2 & "0000" & "0000001010000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
290 => OP_JMP_2 & "0000" & "0000000100100011", -- file: None line: None
291 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
292 => OP_MOVE_2 & "1101" & "0000000000000011", -- file: ./example_3_serial_clock.py line: 14
293 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
294 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
295 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
296 => OP_JMPF_2 & "1100" & "0000000100110011", -- file: None line: None
297 => OP_IMM_2 & "1100" & "0000000000101101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
298 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
299 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
300 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
301 => OP_MOVE_2 & "1101" & "0000000000000011", -- file: ./example_3_serial_clock.py line: 14
302 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
303 => OP_SUB_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 220
304 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
305 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
306 => OP_JMP_2 & "0000" & "0000000100111010", -- file: None line: None
307 => OP_IMM_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
308 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
309 => OP_JMPF_2 & "1100" & "0000000100111010", -- file: None line: None
310 => OP_MOVE_2 & "1100" & "0000000000000011", -- file: ./example_3_serial_clock.py line: 14
311 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
312 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
313 => OP_JMP_2 & "0000" & "0000000100111010", -- file: None line: None
314 => OP_IMM_2 & "1100" & "0010011100010000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
315 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
316 => OP_MOVE_2 & "0111" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
317 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
318 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
319 => OP_MOVE_2 & "1000" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
320 => OP_MOVE_2 & "1100" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
321 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
322 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
323 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
324 => OP_JMPF_2 & "1100" & "0000000101000111", -- file: None line: None
325 => OP_JMP_2 & "0000" & "0000000110000010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
326 => OP_JMP_2 & "0000" & "0000000101000111", -- file: None line: None
327 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
328 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
329 => OP_MOVE_2 & "1001" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
330 => OP_MOVE_2 & "1100" & "0000000000000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
331 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
332 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
333 => OP_GE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 212
334 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
335 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
336 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
337 => OP_JMPF_2 & "1100" & "0000000101010100", -- file: None line: None
338 => OP_JMP_2 & "0000" & "0000000101100001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
339 => OP_JMP_2 & "0000" & "0000000101010100", -- file: None line: None
340 => OP_MOVE_2 & "1100" & "0000000000000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
341 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
342 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
343 => OP_SUB_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 188
344 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
345 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
346 => OP_MOVE_2 & "1100" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
347 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
348 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
349 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
350 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
351 => OP_MOVE_2 & "1001" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
352 => OP_JMP_2 & "0000" & "0000000101001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
353 => OP_MOVE_2 & "1100" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
354 => OP_IMM_2 & "1101" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
355 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
356 => OP_NE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 208
357 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
358 => OP_IMM_2 & "1110" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
359 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
360 => OP_EQ_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 206
361 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
362 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 198
363 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
364 => OP_JMPF_2 & "1100" & "0000000101110001", -- file: None line: None
365 => OP_IMM_2 & "1100" & "1111111111111111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
366 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
367 => OP_MOVE_2 & "1000" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
368 => OP_JMP_2 & "0000" & "0000000101110001", -- file: None line: None
369 => OP_MOVE_2 & "1100" & "0000000000001000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 204
370 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
371 => OP_JMPF_2 & "1100" & "0000000101111011", -- file: None line: None
372 => OP_IMM_2 & "1100" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
373 => OP_MOVE_2 & "1101" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
374 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
375 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 230
376 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
377 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
378 => OP_JMP_2 & "0000" & "0000000101111011", -- file: None line: None
379 => OP_MOVE_2 & "1100" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
380 => OP_IMM_2 & "1101" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
381 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
382 => OP_DIV_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 194
383 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
384 => OP_MOVE_2 & "0111" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
385 => OP_JMP_2 & "0000" & "0000000101000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
386 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
387 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
388 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
389 => OP_IMM_2 & "1100" & "0000000000111010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
390 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
391 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
392 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
393 => OP_MOVE_2 & "1101" & "0000000000000100", -- file: ./example_3_serial_clock.py line: 15
394 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
395 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
396 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
397 => OP_JMPF_2 & "1100" & "0000000110011000", -- file: None line: None
398 => OP_IMM_2 & "1100" & "0000000000101101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
399 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
400 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
401 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
402 => OP_MOVE_2 & "1101" & "0000000000000100", -- file: ./example_3_serial_clock.py line: 15
403 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
404 => OP_SUB_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 220
405 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
406 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
407 => OP_JMP_2 & "0000" & "0000000110011111", -- file: None line: None
408 => OP_IMM_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
409 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
410 => OP_JMPF_2 & "1100" & "0000000110011111", -- file: None line: None
411 => OP_MOVE_2 & "1100" & "0000000000000100", -- file: ./example_3_serial_clock.py line: 15
412 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
413 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
414 => OP_JMP_2 & "0000" & "0000000110011111", -- file: None line: None
415 => OP_IMM_2 & "1100" & "0010011100010000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
416 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
417 => OP_MOVE_2 & "0111" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
418 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
419 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
420 => OP_MOVE_2 & "1000" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
421 => OP_MOVE_2 & "1100" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
422 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
423 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
424 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
425 => OP_JMPF_2 & "1100" & "0000000110101100", -- file: None line: None
426 => OP_JMP_2 & "0000" & "0000000111100111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
427 => OP_JMP_2 & "0000" & "0000000110101100", -- file: None line: None
428 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
429 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
430 => OP_MOVE_2 & "1001" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
431 => OP_MOVE_2 & "1100" & "0000000000000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
432 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
433 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
434 => OP_GE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 212
435 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
436 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
437 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
438 => OP_JMPF_2 & "1100" & "0000000110111001", -- file: None line: None
439 => OP_JMP_2 & "0000" & "0000000111000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
440 => OP_JMP_2 & "0000" & "0000000110111001", -- file: None line: None
441 => OP_MOVE_2 & "1100" & "0000000000000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
442 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
443 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
444 => OP_SUB_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 188
445 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
446 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
447 => OP_MOVE_2 & "1100" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
448 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
449 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
450 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
451 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
452 => OP_MOVE_2 & "1001" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
453 => OP_JMP_2 & "0000" & "0000000110101111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
454 => OP_MOVE_2 & "1100" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
455 => OP_IMM_2 & "1101" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
456 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
457 => OP_NE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 208
458 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
459 => OP_IMM_2 & "1110" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
460 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
461 => OP_EQ_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 206
462 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
463 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 198
464 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
465 => OP_JMPF_2 & "1100" & "0000000111010110", -- file: None line: None
466 => OP_IMM_2 & "1100" & "1111111111111111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
467 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
468 => OP_MOVE_2 & "1000" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
469 => OP_JMP_2 & "0000" & "0000000111010110", -- file: None line: None
470 => OP_MOVE_2 & "1100" & "0000000000001000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 204
471 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
472 => OP_JMPF_2 & "1100" & "0000000111100000", -- file: None line: None
473 => OP_IMM_2 & "1100" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
474 => OP_MOVE_2 & "1101" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
475 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
476 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 230
477 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
478 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
479 => OP_JMP_2 & "0000" & "0000000111100000", -- file: None line: None
480 => OP_MOVE_2 & "1100" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
481 => OP_IMM_2 & "1101" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
482 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
483 => OP_DIV_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 194
484 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
485 => OP_MOVE_2 & "0111" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
486 => OP_JMP_2 & "0000" & "0000000110100101", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
487 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
488 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
489 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
490 => OP_IMM_2 & "1100" & "0000000000111010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
491 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
492 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
493 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
494 => OP_MOVE_2 & "1101" & "0000000000000101", -- file: ./example_3_serial_clock.py line: 16
495 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
496 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
497 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
498 => OP_JMPF_2 & "1100" & "0000000111111101", -- file: None line: None
499 => OP_IMM_2 & "1100" & "0000000000101101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
500 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
501 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
502 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
503 => OP_MOVE_2 & "1101" & "0000000000000101", -- file: ./example_3_serial_clock.py line: 16
504 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
505 => OP_SUB_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 220
506 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
507 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
508 => OP_JMP_2 & "0000" & "0000001000000100", -- file: None line: None
509 => OP_IMM_2 & "1100" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
510 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
511 => OP_JMPF_2 & "1100" & "0000001000000100", -- file: None line: None
512 => OP_MOVE_2 & "1100" & "0000000000000101", -- file: ./example_3_serial_clock.py line: 16
513 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
514 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
515 => OP_JMP_2 & "0000" & "0000001000000100", -- file: None line: None
516 => OP_IMM_2 & "1100" & "0010011100010000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
517 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
518 => OP_MOVE_2 & "0111" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
519 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
520 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
521 => OP_MOVE_2 & "1000" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
522 => OP_MOVE_2 & "1100" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
523 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
524 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
525 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
526 => OP_JMPF_2 & "1100" & "0000001000010001", -- file: None line: None
527 => OP_JMP_2 & "0000" & "0000001001001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
528 => OP_JMP_2 & "0000" & "0000001000010001", -- file: None line: None
529 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
530 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
531 => OP_MOVE_2 & "1001" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
532 => OP_MOVE_2 & "1100" & "0000000000000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
533 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
534 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
535 => OP_GE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 212
536 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
537 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
538 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
539 => OP_JMPF_2 & "1100" & "0000001000011110", -- file: None line: None
540 => OP_JMP_2 & "0000" & "0000001000101011", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
541 => OP_JMP_2 & "0000" & "0000001000011110", -- file: None line: None
542 => OP_MOVE_2 & "1100" & "0000000000000110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 203
543 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
544 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
545 => OP_SUB_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 188
546 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
547 => OP_MOVE_2 & "0110" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
548 => OP_MOVE_2 & "1100" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
549 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
550 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
551 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
552 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
553 => OP_MOVE_2 & "1001" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
554 => OP_JMP_2 & "0000" & "0000001000010100", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
555 => OP_MOVE_2 & "1100" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
556 => OP_IMM_2 & "1101" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
557 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
558 => OP_NE_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 208
559 => OP_MOVE_2 & "1101" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
560 => OP_IMM_2 & "1110" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
561 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
562 => OP_EQ_2 & "1101" & "0000000000001110", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 206
563 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
564 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 198
565 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
566 => OP_JMPF_2 & "1100" & "0000001000111011", -- file: None line: None
567 => OP_IMM_2 & "1100" & "1111111111111111", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
568 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
569 => OP_MOVE_2 & "1000" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
570 => OP_JMP_2 & "0000" & "0000001000111011", -- file: None line: None
571 => OP_MOVE_2 & "1100" & "0000000000001000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 204
572 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
573 => OP_JMPF_2 & "1100" & "0000001001000101", -- file: None line: None
574 => OP_IMM_2 & "1100" & "0000000000110000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
575 => OP_MOVE_2 & "1101" & "0000000000001001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 201
576 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
577 => OP_BOR_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 230
578 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
579 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
580 => OP_JMP_2 & "0000" & "0000001001000101", -- file: None line: None
581 => OP_MOVE_2 & "1100" & "0000000000000111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 200
582 => OP_IMM_2 & "1101" & "0000000000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
583 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
584 => OP_DIV_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 194
585 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
586 => OP_MOVE_2 & "0111" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
587 => OP_JMP_2 & "0000" & "0000001000001010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
588 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
589 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
590 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
591 => OP_IMM_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
592 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
593 => OP_WRITE_1_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/streams.py line: 864
594 => OP_IMM_2 & "1100" & "0000001111101000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
595 => OP_MOVE_2 & "1101" & "0000000000001010", -- file: ./example_3_serial_clock.py line: 17
596 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
597 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
598 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
599 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
600 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
601 => OP_JMPF_2 & "1100" & "0000001001011100", -- file: None line: None
602 => OP_JMP_2 & "0000" & "0000001001111000", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
603 => OP_JMP_2 & "0000" & "0000001001011100", -- file: None line: None
604 => OP_IMM_2 & "1100" & "0000001111101000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
605 => OP_MOVE_2 & "1101" & "0000000000001011", -- file: ./example_3_serial_clock.py line: 18
606 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
607 => OP_GT_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 214
608 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
609 => OP_LNOT_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 180
610 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
611 => OP_JMPF_2 & "1100" & "0000001001100110", -- file: None line: None
612 => OP_JMP_2 & "0000" & "0000001001101110", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 100
613 => OP_JMP_2 & "0000" & "0000001001100110", -- file: None line: None
614 => OP_WAIT_US_2 & "0000" & "0000000000000000", -- file: ./example_3_serial_clock.py line: 45
615 => OP_MOVE_2 & "1100" & "0000000000001011", -- file: ./example_3_serial_clock.py line: 18
616 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
617 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
618 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
619 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
620 => OP_MOVE_2 & "1011" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
621 => OP_JMP_2 & "0000" & "0000001001011100", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
622 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
623 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
624 => OP_MOVE_2 & "1011" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
625 => OP_MOVE_2 & "1100" & "0000000000001010", -- file: ./example_3_serial_clock.py line: 17
626 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
627 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
628 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
629 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
630 => OP_MOVE_2 & "1010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
631 => OP_JMP_2 & "0000" & "0000001001010010", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
632 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
633 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
634 => OP_MOVE_2 & "1010" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
635 => OP_MOVE_2 & "1100" & "0000000000000101", -- file: ./example_3_serial_clock.py line: 16
636 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
637 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
638 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
639 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
640 => OP_MOVE_2 & "0101" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
641 => OP_JMP_2 & "0000" & "0000000100011001", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
642 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
643 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
644 => OP_MOVE_2 & "0101" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
645 => OP_MOVE_2 & "1100" & "0000000000000100", -- file: ./example_3_serial_clock.py line: 15
646 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
647 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
648 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
649 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
650 => OP_MOVE_2 & "0100" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
651 => OP_JMP_2 & "0000" & "0000000100001111", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
652 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
653 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
654 => OP_MOVE_2 & "0100" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
655 => OP_MOVE_2 & "1100" & "0000000000000011", -- file: ./example_3_serial_clock.py line: 14
656 => OP_IMM_2 & "1101" & "0000000000000001", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
657 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
658 => OP_ADD_2 & "1100" & "0000000000001101", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 186
659 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
660 => OP_MOVE_2 & "0011" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
661 => OP_JMP_2 & "0000" & "0000000100000101", -- file: /usr/local/lib/python2.7/dist-packages/chips/__init__.py line: 101
662 => OP_IMM_2 & "1100" & "0000000000000000", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 170
663 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
664 => OP_MOVE_2 & "0011" & "0000000000001100", -- file: /usr/local/lib/python2.7/dist-packages/chips/instruction.py line: 449
665 => OP_JMP_2 & "0000" & "0000000100000101", -- file: ./example_3_serial_clock.py line: 60
666 => OP_JMP_2 & "0000" & "0000001010011010", -- file: None line: None
667 => OP_NOOP_2 & "0000" & "0000000000000000", -- file: None line: None
668 => OP_NOOP_2 & "0000" & "0000000000000000"); -- file: None line: None
  signal MOD_DIV_2        : std_logic;

begin

  process
  begin
    wait until rising_edge(CLK);
    TIMER_1us <= '0';
    TIMER_10us <= '0';
    TIMER_100us <= '0';
    TIMER_1ms <= '0';
    if TIMER_1us_COUNT = 0 then
       TIMER_1us_COUNT <= TIMER_1us_MAX;
       TIMER_1us <= '1';
       if TIMER_10us_COUNT = 0 then
         TIMER_10us_COUNT <= TIMER_10us_MAX;
         TIMER_10us <= '1';
         if TIMER_100us_COUNT = 0 then
           TIMER_100us_COUNT <= TIMER_100us_MAX;
           TIMER_100us <= '1';
           if TIMER_1ms_COUNT = 0 then
             TIMER_1ms_COUNT <= TIMER_1ms_MAX;
             TIMER_1ms <= '1';
           else
             TIMER_1ms_COUNT <= TIMER_1ms_COUNT - 1;
           end if;
         else
           TIMER_100us_COUNT <= TIMER_100us_COUNT - 1;
         end if;
       else
         TIMER_10us_COUNT <= TIMER_10us_COUNT - 1;
       end if;
    else
       TIMER_1us_COUNT <= TIMER_1us_COUNT - 1;
    end if;
    if RST = '1' then
       TIMER_1us_COUNT <= TIMER_1us_MAX;
       TIMER_1us <= '0';
       TIMER_10us_COUNT <= TIMER_10us_MAX;
       TIMER_10us <= '0';
       TIMER_100us_COUNT <= TIMER_100us_MAX;
       TIMER_100us <= '0';
       TIMER_1ms_COUNT <= TIMER_1ms_MAX;
       TIMER_1ms <= '0';
    end if;
  end process;



  --file: ./example_3_serial_clock.py, line: 68
  --serial output port baud rate generator
  process
  begin
    wait until rising_edge(CLK);
    if BAUD_COUNT_4 = CLOCK_DIVIDER_4 then
      BAUD_COUNT_4 <= (others => '0');
      X16CLK_EN_4  <= '1';
    else
      BAUD_COUNT_4 <= BAUD_COUNT_4 + 1;
      X16CLK_EN_4  <= '0';
    end if;
    if RST = '1' then
      BAUD_COUNT_4 <= (others => '0');
      X16CLK_EN_4  <= '0';
    end if;
  end process;

  process
  begin
    wait until rising_edge(CLK);
    case STATE_4 is
      when IDLE =>
        if STREAM_3_STB = '1'  then
          STREAM_3_ACK <= '1';
          DATA_4 <= STREAM_3;
          STATE_4     <= WAIT_EN;
        end if;
      when WAIT_EN =>
        STREAM_3_ACK <= '0';
        if X16CLK_EN_4 = '1' then
          STATE_4 <= START;
        end if;
      when START =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX0;
        end if;
        TX <= '0'; 
      when TX0 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX1;
        end if;
        TX <= DATA_4(0);
      when TX1 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX2;
        end if;
        TX <= DATA_4(1);
      when TX2 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX3;
        end if;
        TX <= DATA_4(2);
      when TX3 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX4;
        end if;
        TX <= DATA_4(3);
      when TX4 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX5;
        end if;
        TX <= DATA_4(4);
      when TX5 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX6;
        end if;
        TX <= DATA_4(5);
      when TX6 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= TX7;
        end if;
        TX <= DATA_4(6);
      when TX7 =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= STOP;
        end if;
        TX <= DATA_4(7);
      when STOP =>
        if X16CLK_EN_4 = '1' then
          STATE_4 <= IDLE;
        end if;
        TX <= '1';
      when others =>
        STATE_4 <= IDLE;
      end case;
    if RST = '1' then
      STREAM_3_ACK <= '0';
      STATE_4 <= IDLE;
    end if; 
  end process;
  --file: ./example_3_serial_clock.py, line: 68
  --stream 3 Resizer(1, 8)
  STREAM_1_ACK <= STREAM_3_ACK;
  STREAM_3_STB <= STREAM_1_STB;
  STREAM_3 <= STREAM_1(7 downto 0);

  --file: ./example_3_serial_clock.py, line: 20
  --serial input port baud rate generator
  process
  begin
    wait until rising_edge(CLK);
    if BAUD_COUNT_0 = CLOCK_DIVIDER_0 then
      BAUD_COUNT_0 <= (others => '0');
      X16CLK_EN_0  <= '1';
    else
      BAUD_COUNT_0 <= BAUD_COUNT_0 + 1;
      X16CLK_EN_0  <= '0';
    end if;
    if RST = '1' then
      BAUD_COUNT_0 <= (others => '0');
      X16CLK_EN_0  <= '0';
    end if;
  end process;

  --synchronise and filter
  process
  begin
    wait until rising_edge(CLK);
    SERIAL_DEGLITCH_0 <= SERIAL_DEGLITCH_0(0) & RX;
    if X16CLK_EN_0 = '1' then
      if SERIAL_DEGLITCH_0(1) = '1' then
        if COUNT_0 = 3 then
          INT_SERIAL_0 <= '1';
        else 
          COUNT_0 <= COUNT_0 + 1;
        end if;
      else
        if COUNT_0 = 0 then
          INT_SERIAL_0 <= '0';
        else
          COUNT_0 <= COUNT_0 - 1;
        end if;
      end if;
    end if;
  end process;

  process
  begin
    wait until rising_edge(CLK);
	 if X16CLK_EN_0 = '1' then 
      if BIT_SPACING_0 = 15 then
        BIT_SPACING_0 <= 0;
      else
        BIT_SPACING_0 <= BIT_SPACING_0 + 1;
      end if;
    end if;
    case STATE_0 is
      when IDLE =>
        BIT_SPACING_0 <= 0;
        if X16CLK_EN_0 = '1' and INT_SERIAL_0 = '0' then
          STATE_0 <= START;
        end if;
      when START =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 7 then
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX0;
        end if; 
      when RX0 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(0) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX1;
        end if;
      when RX1 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(1) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX2;
        end if;
      when RX2 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(2) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX3;
        end if;
      when RX3 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(3) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX4;
        end if;
      when RX4 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(4) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX5;
        end if;
      when RX5 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(5) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX6;
        end if;
      when RX6 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(6) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= RX7;
        end if;
      when RX7 =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
          STREAM_0(7) <= INT_SERIAL_0;
          BIT_SPACING_0 <= 0;
          STATE_0 <= STOP;
        end if;
      when STOP =>
        if X16CLK_EN_0 = '1' and BIT_SPACING_0 = 15 then
            BIT_SPACING_0 <= 0;
            STATE_0 <= OUTPUT_DATA;
        end if;
      when OUTPUT_DATA =>
          STREAM_0_STB <= '1';
          if STREAM_0_ACK = '1' then
            STREAM_0_STB <= '0';
            STATE_0 <= IDLE;
          end if;
      when others =>
        STATE_0 <= IDLE;
    end case;
    if RST = '1' then
      STATE_0 <= IDLE;
      STREAM_0_STB <= '0';
    end if; 
  end process;

  -- PIPELINE STAGE 0 - INSTRUCTION FETCH
  process
    variable INSTRUCTION : std_logic_vector(24 downto 0);
  begin
    wait until rising_edge(CLK);
      INSTRUCTION := INSTRUCTIONS_2(to_integer(PC_2));
      SRCA_0_2      <= INSTRUCTION(19 downto 16);
      SRCB_0_2      <= INSTRUCTION(3 downto 0);
      IMMEDIATE_0_2 <= INSTRUCTION(15 downto 0);
      OPERATION_0_2 <= INSTRUCTION(24 downto 20);
  end process;

  -- PIPELINE STAGE 1 - REGISTER FETCH
  process
    variable REGISTERS : REGISTERS_TYPE_2;
  begin
    wait until rising_edge(CLK);
    if REGISTER_EN_3_2 = '1' then
      REGISTERS(to_integer(unsigned(DEST_3_2))) := RESULT_3_2;
    end if;
    if STATE_2 = EXECUTE or STATE_2 = STALL then
      REGA_1_2      <= REGISTERS(to_integer(unsigned(SRCA_0_2)));
      REGB_1_2      <= REGISTERS(to_integer(unsigned(SRCB_0_2)));
      DEST_1_2      <= SRCA_0_2;
      OPERATION_1_2 <= OPERATION_0_2;
      IMMEDIATE_1_2 <= IMMEDIATE_0_2;
    end if;
  end process;

  -- PIPELINE STAGE 2 - PRE_EXECUTE
  REGA_2_2      <= REGA_1_2;
  REGB_2_2      <= REGB_1_2;
  DEST_2_2      <= DEST_1_2;
  OPERATION_2_2 <= OPERATION_1_2;
  IMMEDIATE_2_2 <= IMMEDIATE_1_2;

  -- PIPELINE STAGE 3 - EXECUTE
  process
    variable MODULO       : unsigned(15 downto 0);
    variable STALL_COUNT  : integer range 0 to 1;
    variable FLAG_EQ : std_logic;
    variable FLAG_NE : std_logic;
    variable FLAG_GT : std_logic;
    variable FLAG_GE : std_logic;
  begin
    wait until rising_edge(CLK);
    REGISTER_EN_3_2 <= '0';
    case STATE_2 is
      when STALL =>
        PC_2 <= PC_2 + 1;
        if STALL_COUNT = 0 then
          STATE_2 <= EXECUTE;
        else
          STALL_COUNT := STALL_COUNT - 1;
        end if;
      when EXECUTE =>
        DEST_3_2 <= DEST_2_2;
        RESULT_3_2 <= REGA_2_2;
        PC_2 <= PC_2 + 1;

        --share comparator logic
        if REGA_2_2 = REGB_2_2 then
          FLAG_EQ := '1';
        else
          FLAG_EQ := '0';
        end if;

        FLAG_NE := not FLAG_EQ;

        if signed(REGA_2_2) > signed(REGB_2_2) then
          FLAG_GT := '1';
        else
          FLAG_GT := '0';
        end if;

        FLAG_GE := FLAG_GT or FLAG_EQ;

        --execute instructions
        case OPERATION_2_2 is
          when OP_MOVE_2 => 
            RESULT_3_2 <= REGB_2_2;
            REGISTER_EN_3_2 <= '1';
          when OP_NOOP_2 => 
            REGISTER_EN_3_2 <= '0';
            RESULT_3_2 <= RESULT_3_2;
          when OP_MUL_2  => 
            RESULT_3_2 <= STD_RESIZE( MUL(REGA_2_2, REGB_2_2), 16);
            REGISTER_EN_3_2 <= '1';
          when OP_ADD_2  => 
            RESULT_3_2 <= STD_RESIZE( ADD(REGA_2_2, REGB_2_2), 16);
            REGISTER_EN_3_2 <= '1';
          when OP_SUB_2  => 
            RESULT_3_2 <= STD_RESIZE( SUB(REGA_2_2, REGB_2_2), 16);
            REGISTER_EN_3_2 <= '1';
          when OP_BAND_2 => 
            RESULT_3_2 <= STD_RESIZE(BAND(REGA_2_2, REGB_2_2), 16);
            REGISTER_EN_3_2 <= '1';
          when OP_BOR_2  => 
            RESULT_3_2 <= STD_RESIZE( BOR(REGA_2_2, REGB_2_2), 16);
            REGISTER_EN_3_2 <= '1';
          when OP_EQ_2   => 
            RESULT_3_2 <= (others => FLAG_EQ);
            REGISTER_EN_3_2 <= '1';
          when OP_NE_2   => 
            RESULT_3_2 <= (others => FLAG_NE);
            REGISTER_EN_3_2 <= '1';
          when OP_GT_2   => 
            RESULT_3_2 <= (others => FLAG_GT);
            REGISTER_EN_3_2 <= '1';
          when OP_GE_2   => 
            RESULT_3_2 <= (others => FLAG_GE);
            REGISTER_EN_3_2 <= '1';
          when OP_IMM_2  => 
            RESULT_3_2 <= IMMEDIATE_2_2;
            REGISTER_EN_3_2 <= '1';
          when OP_LNOT_2  => 
            RESULT_3_2 <= STD_RESIZE( LNOT(REGA_2_2), 16);
            REGISTER_EN_3_2 <= '1';
          when OP_JMP_2 =>
            STATE_2 <= STALL;
            STALL_COUNT := 1;
            PC_2 <= resize(unsigned(IMMEDIATE_2_2), 10);
          when OP_JMPF_2 =>
            if RESULT_3_2 = "0000000000000000" then
              STATE_2 <= STALL;
              STALL_COUNT := 1;
              PC_2 <= resize(unsigned(IMMEDIATE_2_2), 10);
            end if;
          when OP_WAIT_US_2 =>
            STATE_2 <= WAIT_US;
            PC_2 <= PC_2;
          when OP_DIV_2 =>
            MOD_DIV_2 <= '1';
            A_2 <= std_logic_vector(abs(signed(REGA_2_2)));
            B_2 <= std_logic_vector(abs(signed(REGB_2_2)));
            SIGN_2 <= REGA_2_2(15) xor REGB_2_2(15);
            STATE_2 <= DIVIDE_0;
            PC_2 <= PC_2;
          when OP_WRITE_1_2 =>
            STATE_2 <= WRITE_STREAM_1;
            STREAM_1 <= STD_RESIZE(REGA_2_2, 16);
            STREAM_1_STB <= '0';
            PC_2 <= PC_2;
          when OP_READ_0_2 =>
            STATE_2 <= READ_STREAM_0;
            PC_2 <= PC_2;
          when others => null;
        end case;

      when DIVIDE_0 =>
        QUOTIENT_2 <= (others => '0');
        SHIFTER_2 <= (others => '0');
        SHIFTER_2(0) <= A_2(15);
        A_2 <= A_2(14 downto 0) & '0';
        COUNT_2 <= 15;
        STATE_2 <= DIVIDE_1;
      when DIVIDE_1 => --subtract
       --if SHIFTER - B is positive or zero
       if REMAINDER_2(15) = '0' then
         SHIFTER_2(15 downto 1) <= REMAINDER_2(14 downto 0);
       else
         SHIFTER_2(15 downto 1) <= SHIFTER_2(14 downto 0);
       end if;
       SHIFTER_2(0) <= A_2(15);
       A_2 <= A_2(14 downto 0) & '0';
       QUOTIENT_2 <= QUOTIENT_2(14 downto 0) & not(REMAINDER_2(15));
       if COUNT_2 = 0 then
         STATE_2 <= DIVIDE_2;
       else
         COUNT_2 <= COUNT_2 - 1;
       end if;
      when DIVIDE_2 =>
       REGISTER_EN_3_2 <= '1';
       if MOD_DIV_2 = '1' then --if division
         if SIGN_2 = '1' then --if negative
           RESULT_3_2 <= std_logic_vector(-signed(QUOTIENT_2));
         else
           RESULT_3_2 <= QUOTIENT_2;
         end if;
       else
         MODULO := unsigned(SHIFTER_2)/2;
         if SIGN_2 = '1' then --if negative
           RESULT_3_2 <= std_logic_vector(0-MODULO);
         else
           RESULT_3_2 <= std_logic_vector(  MODULO);
         end if;
       end if;
       STATE_2 <= EXECUTE;
       PC_2 <= PC_2 + 1;
      when READ_STREAM_0 =>
        if STREAM_0_STB = '1' then
          STREAM_0_ACK <= '1';
          REGISTER_EN_3_2 <= '1';
          RESULT_3_2 <= STD_RESIZE(STREAM_0, 16);
          STATE_2 <= ACK_STREAM_0;
        end if;
      when ACK_STREAM_0 =>
        STREAM_0_ACK <= '0';
        STATE_2 <= EXECUTE;
        PC_2 <= PC_2 + 1;
      when WRITE_STREAM_1 =>
        STREAM_1_STB <= '1';
        if STREAM_1_ACK = '1' then
          STREAM_1_STB <= '0';
          STATE_2 <= EXECUTE;
          PC_2 <= PC_2 + 1;
        end if;
      when WAIT_US =>
        if TIMER_1uS = '1'then
          PC_2 <= PC_2 + 1;
          STATE_2 <= EXECUTE;
        end if;
    end case;

    if RST = '1' then
      STATE_2 <= STALL;
      STALL_COUNT := 1;
      PC_2 <= "0000000000";
      STREAM_0_ACK <= '0';
      STREAM_1_STB <= '0';
    end if;
  end process;


  --subtractor
  REMAINDER_2 <= std_logic_vector(unsigned(SHIFTER_2) - resize(unsigned(B_2), 16));

end architecture RTL;

--+============================================================================+
--|                       **END OF AUTO GENERATED CODE**                       |
--+============================================================================+